### ISSUE TITLE
User should be authenticated to send a mail

### ISSUE THREAD

**Issue by McMoudi** [LozziKit/microservice-mail#1]
Authentication should be mandatory to use this service as to ensure minimum security, even if the service is aimed at being run in a "protected" environment.

**Comment by Farenjihn** [comment]
This is an interesting suggestion.

As of yet, this service will __only__ run inside of the organisation's network and as such does not need any kind of authentication to ensure potential attackers won't steal our identity. Moreover, it would seem you are not part of said organisation. Keep in mind that I think this way solely because this application is unlikely to really end up in a real production environment.

That said, I will appreciate, review, and potentially merge a pull request if you wish to provide one!

Closing.
